import { useEffect, useMemo, useRef, useState } from "react";
import { Link, useNavigate } from "@tanstack/react-router";
import { motion } from "motion/react";
import {
  AlertTriangle, ArrowLeft, ArrowRight, Bell, BookOpen, Camera, Check, ChevronRight,
  CircleUserRound, Ear, Eye, HeartHandshake, Info, Languages, Map, MapPin, Menu,
  MessageCircle, Mic, MoreHorizontal, Navigation, Pause, Play, RotateCcw, Send,
  Settings, ShieldAlert, Sparkles, Type, Volume2, Waves, X, Zap,
} from "lucide-react";
import { Button } from "@/components/ui/button";
import { BottomNavigation } from "@/components/layout/BottomNavigation";
import { INAIAvatar } from "@/components/inai/INAIAvatar";
import { ModeBadge } from "@/components/inai/ModeBadge";
import { useAccessibilityStore, selectedNeeds, type Need } from "@/stores/accessibility-store";
import { useContextStore } from "@/stores/context-store";
import { useSessionStore } from "@/stores/session-store";
import { resolveDashboard } from "@/lib/inai/dashboard";
import { BrowserTTSService } from "@/services/tts";
import { serviceRegistry } from "@/services/service-registry";
import avatarAsset from "@/assets/inai-avatar.png.asset.json";
import campusImage from "@/assets/campus-walkway.jpg";
import vehicleImage from "@/assets/vehicle-alert.jpg";

const tts = new BrowserTTSService();
const footer = <p className="py-5 text-center text-[10px] font-bold uppercase tracking-[.25em] text-muted-foreground">People · Access · Opportunities · Together</p>;
const needInfo = {
  visual: { label: "Visual", title: "Visual Assistance", text: "Help me understand my surroundings", icon: Eye, tone: "visual" },
  hearing: { label: "Hearing", title: "Hearing Assistance", text: "Help me understand sounds & communication", icon: Ear, tone: "hearing" },
  speech: { label: "Speech", title: "Speech Assistance", text: "Help me communicate with others", icon: MessageCircle, tone: "speech" },
} as const;
const toneClasses = { visual: "bg-visual-tint text-visual border-visual/20", hearing: "bg-hearing-tint text-hearing border-hearing/20", speech: "bg-speech-tint text-speech border-speech/20" };

function DeviceBar() { return <div aria-hidden="true" className="flex h-10 items-center justify-between px-6 text-sm font-extrabold"><span>9:41</span><span className="flex items-center gap-1">▮▮▮ ◉ ▰</span></div>; }
function Dots({ active }: { active: number }) { return <div className="flex justify-center gap-2" aria-label={`Step ${active + 1} of 3`}>{[0,1,2].map(i=><span key={i} className={`h-1.5 w-12 rounded-full ${i<=active ? "bg-primary" : "bg-primary-tint"}`}/>)}</div>; }
function PageFrame({ children, nav = false, className = "" }: { children: React.ReactNode; nav?: boolean; className?: string }) { return <div className="min-h-dvh bg-canvas"><div className={`mx-auto flex min-h-dvh max-w-3xl flex-col overflow-hidden bg-background shadow-inai ${className}`}><DeviceBar/>{children}{nav && <BottomNavigation/>}</div></div>; }
function TopBar({ title, subtitle, icon: Icon = Sparkles, more = false }: { title: string; subtitle: string; icon?: typeof Eye; more?: boolean }) { return <header className="grid grid-cols-[3rem_minmax(0,1fr)_3rem] items-center gap-2 px-5 py-2"><Link to="/home" aria-label="Back to home" className="grid size-12 place-items-center rounded-full bg-primary-tint text-primary"><ArrowLeft/></Link><div className="flex min-w-0 items-center justify-center gap-3"><span className="grid size-11 shrink-0 place-items-center rounded-full bg-primary-tint text-primary"><Icon/></span><div className="min-w-0"><p className="truncate text-lg font-extrabold text-ink">{title}</p><p className="truncate text-xs text-muted-foreground">{subtitle}</p></div></div><Link to="/settings" aria-label="Settings" className="grid size-12 place-items-center rounded-full bg-primary-tint text-primary">{more ? <MoreHorizontal/> : <Settings/>}</Link></header>; }
function AvatarImage({ className = "" }: { className?: string }) { return <img src={avatarAsset.url} alt="INAI, your accessibility companion" className={`object-contain ${className}`}/>; }
function SpeechCard({ children, live = false }: { children: React.ReactNode; live?: boolean }) { return <div className="rounded-card border border-primary/10 bg-primary-tint p-5 shadow-inai"><div className="mb-2 flex items-center justify-between"><span className="flex items-center gap-2 font-extrabold text-primary"><Waves className="size-5"/> INAI</span>{live && <span className="rounded-full bg-background px-3 py-1 text-xs font-bold text-primary">● Speaking...</span>}</div><div className="text-lg font-semibold leading-relaxed text-ink">{children}</div></div>; }
function NeedCard({ need, selected, confirm = false, onClick }: { need: Need; selected: boolean; confirm?: boolean; onClick?: () => void }) { const item=needInfo[need]; const Icon=item.icon; return <button type="button" onClick={onClick} aria-pressed={selected} className={`relative min-h-56 rounded-card border p-5 text-center shadow-inai transition ${toneClasses[item.tone]} ${!selected && confirm ? "opacity-45 grayscale" : ""}`}><span className={`absolute right-4 top-4 grid size-7 place-items-center rounded-full border-2 ${selected ? "border-transparent bg-current text-primary-foreground" : "border-muted-foreground"}`}>{selected && <Check className="size-4"/>}</span><span className="mx-auto mt-5 grid size-16 place-items-center rounded-full bg-background/60"><Icon className="size-9"/></span><strong className="mt-4 block text-xl text-ink">{confirm ? item.title : item.label}</strong><span className="mt-2 block text-sm leading-snug text-muted-foreground">{item.text}</span></button>; }

export function SplashScreen() {
  const navigate=useNavigate();
  useEffect(()=>{ const id=window.setTimeout(()=>void navigate({to:"/onboarding/intro"}),2600); return()=>window.clearTimeout(id); },[navigate]);
  return <PageFrame><main className="relative flex flex-1 flex-col items-center justify-center px-8 text-center"><p className="absolute left-8 top-16 rotate-[-5deg] font-hand text-3xl text-primary/70">Hi!<br/>I’m INAI</p><p className="absolute right-8 top-28 rotate-[4deg] font-hand text-xl text-primary/70">Here for you,<br/>Always ♡</p><AvatarImage className="h-[48vh] w-full"/><h1 className="text-6xl font-extrabold text-primary">INAI</h1><p className="mt-2 text-lg text-muted-foreground">Your intelligent accessibility companion</p><div className="mt-8 h-2 w-60 overflow-hidden rounded-full bg-primary-tint"><motion.div className="h-full rounded-full bg-primary" initial={{width:"8%"}} animate={{width:"100%"}} transition={{duration:2.4}}/></div><p className="mt-4 text-sm text-muted-foreground">Building a more inclusive tomorrow...</p></main>{footer}</PageFrame>;
}
export function IntroScreen() { return <PageFrame><main className="flex flex-1 flex-col px-6 pb-4"><div className="flex items-center justify-between"><span/><Link to="/onboarding/setup" className="min-h-12 px-4 py-3 font-semibold text-muted-foreground">Skip <ChevronRight className="inline size-4"/></Link></div><div className="mt-1 grid grid-cols-[1fr_1.1fr] items-center"><p className="rotate-[-5deg] font-hand text-3xl leading-tight text-primary/70">Hello!<br/>I’m INAI ♡<br/><span className="text-xl">Your companion for a more inclusive tomorrow.</span></p><SpeechCard><strong>Hi! I’m INAI.</strong><br/><span className="font-normal">I’m here to make your everyday environment easier to understand and interact with.</span></SpeechCard></div><AvatarImage className="mx-auto -mt-8 h-[45vh] w-full"/><div className="grid grid-cols-4 gap-2">{[[Volume2,"Speaks"],[HeartHandshake,"Signs"],[MessageCircle,"Shows Text"],[CircleUserRound,"Always With You"]].map(([I,l])=>{const Icon=I as typeof Eye; return <div key={String(l)} className="rounded-control border border-line bg-background p-3 text-center shadow-inai"><Icon className="mx-auto size-7 text-primary"/><p className="mt-2 text-xs font-bold text-ink">{String(l)}</p></div>})}</div><p className="mt-6 text-center text-xs font-bold uppercase tracking-[.25em] text-muted-foreground">See · Hear · Speak · Belong</p><p className="mt-2 text-center text-sm text-muted-foreground">Together, for a more inclusive world.</p><div className="mt-5"><Dots active={0}/></div><div className="mt-auto flex justify-end pt-5"><Button asChild className="w-52 rounded-full"><Link to="/onboarding/setup">Next <ArrowRight/></Link></Button></div></main></PageFrame>; }
export function SetupScreen() { const profile=useAccessibilityStore(s=>s.profile); const setNeed=useAccessibilityStore(s=>s.setNeed); const navigate=useNavigate(); const count=selectedNeeds(profile).length; return <PageFrame><main className="flex flex-1 flex-col px-6 pb-2"><div className="grid grid-cols-[3rem_1fr_3rem] items-center"><Link to="/onboarding/intro" className="grid size-12 place-items-center rounded-full bg-primary-tint text-primary"><ArrowLeft/></Link><Dots active={1}/><span/></div><div className="mt-3 grid grid-cols-[1.1fr_.9fr] items-center gap-3"><AvatarImage className="h-48 w-full"/><SpeechCard><strong>Hi! I’m INAI.</strong><br/><span className="font-normal text-base">Tell me how I can support you. Choose one or more options.</span></SpeechCard></div><h1 className="text-center text-3xl font-extrabold text-ink">How can I support you?</h1><p className="mt-2 text-center text-muted-foreground">Choose the areas where you need assistance.</p><div className="mt-5 grid grid-cols-3 gap-3">{(["visual","hearing","speech"] as Need[]).map(n=><NeedCard key={n} need={n} selected={profile[n]} onClick={()=>setNeed(n,!profile[n])}/>)}</div><div className="mt-5 flex gap-3 rounded-card bg-primary-tint p-4"><Info className="shrink-0 text-primary"/><p className="text-sm"><strong className="text-ink">You can select more than one</strong><br/><span className="text-muted-foreground">INAI will personalize the app for you.</span></p></div><Button disabled={!count} className="mt-5 w-full rounded-full" onClick={()=>void navigate({to:"/onboarding/confirm"})}>Continue <ArrowRight/></Button>{footer}</main></PageFrame>; }
export function ConfirmScreen() { const profile=useAccessibilityStore(s=>s.profile); return <PageFrame><main className="flex flex-1 flex-col px-6"><div className="grid grid-cols-[3rem_1fr_3rem] items-center"><Link to="/onboarding/setup" className="grid size-12 place-items-center rounded-full bg-primary-tint text-primary"><ArrowLeft/></Link><Dots active={2}/><span/></div><div className="mt-2 flex items-center justify-center gap-4"><AvatarImage className="h-48 w-48"/><SpeechCard><strong>Nice!</strong><br/>I’ll customize INAI for you.</SpeechCard></div><h1 className="text-center text-3xl font-extrabold">Your INAI experience</h1><p className="mt-1 text-center text-muted-foreground">You’ve selected the following assistance:</p><div className="mt-5 grid grid-cols-3 gap-3">{(["visual","hearing","speech"] as Need[]).map(n=><NeedCard key={n} need={n} selected={profile[n]} confirm/>)}</div><div className="mt-5 grid grid-cols-[5rem_1fr] items-center rounded-card bg-primary-tint pr-5"><AvatarImage className="size-20"/><p className="font-semibold text-primary">I’ll personalize your experience around these needs. ♡</p></div><Button asChild className="mt-5 w-full rounded-full"><Link to="/home">Continue <ArrowRight/></Link></Button>{footer}</main></PageFrame>; }

function ModuleCard({ title, icon: Icon, children, to, tone="visual" }: { title:string; icon:typeof Eye; children:React.ReactNode; to:string; tone?:keyof typeof toneClasses }) { return <Link to={to} className="block rounded-card border border-line bg-background p-4 shadow-inai"><div className="flex items-center gap-3"><span className={`grid size-11 place-items-center rounded-full ${toneClasses[tone]}`}><Icon/></span><strong className="text-ink">{title}</strong><span className="ml-auto rounded-full bg-hearing-tint px-2 py-1 text-[10px] font-bold text-hearing">● Live</span></div><div className="mt-3">{children}</div></Link>; }
export function HomeScreen() { const profile=useAccessibilityStore(s=>s.profile); const modules=resolveDashboard(profile,{now:Date.now()}).filter(m=>m.id!=="inaiStatus"); return <PageFrame nav><main className="flex-1 px-5 pb-6"><div className="grid grid-cols-[1fr_11rem] items-start"><div className="pt-4"><h1 className="text-3xl font-extrabold">Good morning,<br/>Sanjai 👋</h1><p className="mt-2 text-muted-foreground">A more inclusive day starts here.</p></div><AvatarImage className="h-52 w-full"/></div><SpeechCard>I’m monitoring your surroundings and listening for important sounds. I’m here with you!</SpeechCard><div className="mt-5 grid gap-4 sm:grid-cols-2">{modules.map(m=>{ if(m.id==="environment") return <ModuleCard key={m.id} title="Environment (Vision)" icon={Eye} to="/vision"><div className="relative h-40 overflow-hidden rounded-control"><img src={campusImage} alt="Campus path" className="size-full object-cover"/><span className="absolute left-3 top-4 rounded bg-primary px-2 py-1 text-xs font-bold text-primary-foreground">Person 3 m</span><span className="absolute right-3 top-3 rounded bg-destructive px-2 py-1 text-xs font-bold text-destructive-foreground">Stairs 4 m</span></div></ModuleCard>; if(m.id==="soundAwareness") return <ModuleCard key={m.id} title="Sound (Hearing)" icon={Ear} to="/sound" tone="hearing"><div className="rounded-control bg-hearing-tint p-5 text-center text-2xl text-hearing">▂▅▃▇▅▂▆▃▇</div><p className="mt-3 font-bold text-destructive">Emergency siren detected</p></ModuleCard>; if(m.id==="transcription") return <ModuleCard key={m.id} title="Live Transcription" icon={MessageCircle} to="/transcribe"><p className="text-lg">“Please move to the main entrance.”</p></ModuleCard>; if(m.id==="communication") return <ModuleCard key={m.id} title="Communication" icon={MessageCircle} to="/communicate" tone="speech"><p className="text-muted-foreground">Speak, type, or choose a phrase.</p></ModuleCard>; return <ModuleCard key={m.id} title={m.title} icon={MapPin} to="/map"><p className="text-muted-foreground">Block B, SKCET · Accessible route 80 m</p></ModuleCard>})}</div><Link to="/inai" className="mt-5 flex min-h-16 items-center justify-between rounded-card bg-primary-tint px-5 font-extrabold text-primary"><span className="flex items-center gap-2"><Sparkles/>Ask INAI</span><ChevronRight/></Link></main></PageFrame>; }

function CameraScene({ live=false }: { live?:boolean }) { return <div className={`relative overflow-hidden ${live ? "min-h-[62vh]" : "h-[52vh] rounded-b-card"}`}><img src={campusImage} alt="Live view of a campus path" className="absolute inset-0 size-full object-cover"/><div className="absolute inset-x-[40%] bottom-0 h-[46%] bg-hearing/35 [clip-path:polygon(40%_0,60%_0,100%_100%,0_100%)]"/><span className="absolute left-[20%] top-[25%] rounded-md bg-primary px-3 py-1 text-sm font-bold text-primary-foreground">Person<br/>3 m</span><span className="absolute right-[10%] top-[32%] rounded-md bg-destructive px-3 py-1 text-sm font-bold text-destructive-foreground">Stairs<br/>3 m</span><span className="absolute bottom-[12%] left-1/2 -translate-x-1/2 rounded-control bg-hearing px-4 py-2 font-bold text-primary-foreground">✓ Path is clear</span><span className="absolute right-4 top-4 rounded-full bg-ink/80 px-4 py-2 text-xs font-bold text-primary-foreground">● Live {live ? "Monitoring" : "Analysis"}</span></div>; }
export function VisionScreen() { const [tip,setTip]=useState(true); const [spoken,setSpoken]=useState(false); const speak=()=>{setSpoken(true); void tts.speak("Stairs are 3 meters ahead. The pathway is clear on your right.",{priority:"guidance",interrupt:true}).finally(()=>setSpoken(false));}; return <PageFrame nav><TopBar title="AI Vision" subtitle="Understanding your surroundings" icon={Eye} more/><main className="flex-1"><CameraScene/><div className="grid grid-cols-[8rem_1fr] items-center px-5"><AvatarImage className="h-40 w-full"/><SpeechCard live={spoken}>Stairs are 3 meters ahead. The pathway is clear on your right.</SpeechCard></div><div className="grid grid-cols-3 gap-3 px-5">{[["Stairs","3 meters ahead"],["Pathway","Clear on right"],["Door","6 meters ahead"]].map(([a,b])=><div key={a} className="rounded-control border border-line p-3"><strong>{a}</strong><p className="mt-1 text-xs text-muted-foreground">{b}</p></div>)}</div><div className="mt-4 grid grid-cols-3 gap-3 px-5"><Button variant="outline" onClick={speak}><Waves/>Describe More</Button><Button asChild><Link to="/guidance"><Navigation/>Navigation</Link></Button><Button variant="outline" onClick={()=>alert("Photo captured for this session.")}><Camera/>Take Photo</Button></div>{tip&&<div className="mx-5 mt-4 flex items-center gap-3 rounded-card bg-primary-tint p-4 text-sm text-primary"><Info/><span>Tip: Follow the highlighted path for the safest route.</span><Button variant="ghost" size="icon" onClick={()=>setTip(false)} className="ml-auto"><X/></Button></div>}</main></PageFrame>; }
export function LiveVisionScreen() { return <PageFrame nav><main className="relative flex-1"><div className="absolute left-5 top-3 z-10 flex items-center gap-2 text-primary-foreground"><Menu/><strong>INAI</strong></div><CameraScene live/><div className="relative -mt-24 px-5"><div className="grid grid-cols-[8rem_1fr] items-end"><AvatarImage className="h-44 w-full"/><SpeechCard>I’m monitoring your surroundings. The path ahead is clear.</SpeechCard></div><div className="mt-3 grid grid-cols-2 gap-3"><Link to="/sound" className="rounded-control bg-background p-4 shadow-inai"><strong className="text-hearing">Audio Event</strong><p>People talking nearby</p></Link><Link to="/map" className="rounded-control bg-background p-4 shadow-inai"><strong className="text-primary">Location</strong><p>Academic Block B</p></Link></div></div></main></PageFrame>; }
export function AlertScreen() { const navigate=useNavigate(); useEffect(()=>{ if(navigator.vibrate) navigator.vibrate([300,150,300]); void tts.speak("Warning. A vehicle is approaching from your right. Please maintain distance.",{priority:"emergency",interrupt:true}); return()=>tts.cancel();},[]); return <PageFrame><main className="relative flex flex-1 flex-col bg-background"><img src={vehicleImage} alt="Vehicle approaching from the right" className="absolute inset-0 h-[65%] w-full object-cover opacity-35"/><div className="relative z-10 px-5 text-center"><div className="mx-auto mt-4 grid size-24 place-items-center rounded-full bg-speech-tint text-destructive"><AlertTriangle className="size-14"/></div><p className="mt-2 text-2xl font-extrabold text-destructive">WARNING</p><h1 className="text-4xl font-extrabold text-destructive">VEHICLE APPROACHING</h1><p className="text-2xl font-bold">From your right</p><p className="text-lg text-muted-foreground">Maintain distance</p></div><div className="relative z-10 mt-auto px-5"><div className="grid grid-cols-[9rem_1fr] items-end"><AvatarImage className="h-64 w-full"/><div className="mb-6 rounded-card bg-background p-5 shadow-inai"><strong className="text-destructive">INAI</strong><p className="mt-2 text-xl font-bold">A vehicle is approaching from your right. Please maintain distance.</p></div></div><div className="grid grid-cols-4 gap-2">{[[Eye,"See","Vehicle detected"],[Sparkles,"Understand","From your right"],[ArrowLeft,"Decide","Move slightly left"],[Navigation,"Guide","Stay safe"]].map(([I,a,b])=>{const Icon=I as typeof Eye;return <div key={String(a)} className="rounded-control bg-background p-3 text-center shadow-inai"><Icon className="mx-auto text-primary"/><strong className="block text-xs">{String(a)}</strong><span className="text-[10px] text-muted-foreground">{String(b)}</span></div>})}</div><Button className="my-6 w-full rounded-full bg-destructive text-destructive-foreground hover:bg-destructive/90" onClick={()=>{tts.cancel();void navigate({to:"/home"})}}><Volume2/>Got it</Button></div></main></PageFrame>; }

export function SoundScreen() { const [all,setAll]=useState(false); return <PageFrame nav><TopBar title="Hearing Assistance" subtitle="Stay Aware. Stay Confident." icon={Ear} more/><main className="flex-1 px-5"><div className="flex items-start justify-between"><div><h1 className="text-3xl font-extrabold">Sound Awareness</h1><p className="text-muted-foreground">Important sounds around you.</p></div><span className="rounded-full bg-hearing-tint px-3 py-2 text-xs font-bold text-hearing">● Live Listening</span></div><div className="relative mx-auto mt-6 aspect-square max-w-sm rounded-full border border-primary/20 bg-primary-tint"><div className="absolute inset-[14%] rounded-full border border-primary/20"/><div className="absolute inset-[30%] rounded-full border border-primary/20"/><span className="absolute left-1/2 top-2 -translate-x-1/2 text-xs">Front</span><span className="absolute left-1 top-1/2 -translate-y-1/2 text-xs">Left</span><span className="absolute right-1 top-1/2 -translate-y-1/2 text-xs">Right</span><span className="absolute bottom-2 left-1/2 -translate-x-1/2 text-xs">Back</span><span className="absolute left-[15%] top-[44%] grid size-14 place-items-center rounded-full bg-destructive text-destructive-foreground shadow-inai"><Bell/></span><span className="absolute left-[64%] top-[23%]">● People talking</span><span className="absolute left-[70%] top-[67%]">● Vehicle</span></div><div className="mt-5 rounded-card bg-speech-tint p-5"><p className="text-xs font-bold text-destructive">INAI HEARD SOMETHING</p><h2 className="text-2xl font-extrabold text-destructive">Emergency siren</h2><p>Direction: Left · Distance: Approx. 20 m <ModeBadge mode="MOCK"/></p></div><div className="mt-3 grid grid-cols-[8rem_1fr] items-end"><AvatarImage className="h-44"/><SpeechCard>“An emergency siren is approaching from your left. It’s about 20 meters away. Please be aware.”</SpeechCard></div><section className="mt-4 rounded-card bg-primary-tint p-4"><h2 className="font-extrabold">What you can do</h2><div className="mt-3 grid grid-cols-4 gap-2 text-center text-xs">{["Move left slowly","Check surroundings","Wait if needed","Tell me more"].map(x=><button key={x} className="min-h-20 rounded-control bg-background p-2 shadow-sm">{x}</button>)}</div></section><Button variant="outline" className="mt-4 w-full" onClick={()=>setAll(!all)}><Waves/>Show All Detected Sounds<ChevronRight className="ml-auto"/></Button>{all&&<p className="mt-3 text-sm text-muted-foreground">Emergency siren · People talking · Vehicle</p>}</main></PageFrame>; }
export function TranscribeScreen() { const [listening,setListening]=useState(false); const [saved,setSaved]=useState(false); return <PageFrame nav><TopBar title="Live Transcription" subtitle="Follow every conversation" icon={MessageCircle}/><main className="flex-1 px-5"><div className="relative mt-2 h-52 overflow-hidden rounded-card bg-primary-tint"><AvatarImage className="mx-auto h-full"/><span className="absolute bottom-3 left-3 rounded-full bg-background px-3 py-1 text-xs font-bold">Speaker 1</span></div><blockquote className="mt-5 rounded-card border border-line bg-background p-6 text-2xl font-bold shadow-inai">“Your classroom has been moved to Block B.”</blockquote><SpeechCard>Important detail: <strong>Block B → Classroom</strong></SpeechCard><div className="mt-5 grid grid-cols-4 gap-2">{[[BookOpen,"Save Note"],[MapPin,"Show on Map"],[RotateCcw,"Repeat"],[Languages,"Translate"]].map(([I,l])=>{const Icon=I as typeof Eye;return <Button key={String(l)} variant="outline" className="h-20 flex-col whitespace-normal text-xs" onClick={()=>String(l)==="Save Note"&&setSaved(true)}><Icon/>{saved&&String(l)==="Save Note"?"Saved":String(l)}</Button>})}</div><Button className="mt-6 w-full rounded-full" onClick={()=>setListening(!listening)}><Mic/>{listening?"Stop Listening":"Keep Listening"}</Button></main></PageFrame>; }
