import { Check, Ear, Eye, MessageCircle, ShieldCheck, Sparkles } from "lucide-react";
import { Button } from "@/components/ui/button";
import { selectedNeeds, useAccessibilityStore, type Need } from "@/stores/accessibility-store";
import { resolveDashboard } from "@/lib/inai/dashboard";
import { INAIAvatar } from "./INAIAvatar";
import { ModeBadge } from "./ModeBadge";
import { CaptionRegion } from "./CaptionRegion";
const options = [
  { id: "visual" as const, label: "Visual", copy: "Describe surroundings and guide safely", Icon: Eye, tone: "bg-visual-tint text-visual" },
  { id: "hearing" as const, label: "Hearing", copy: "Show important sounds and live speech", Icon: Ear, tone: "bg-hearing-tint text-hearing" },
  { id: "speech" as const, label: "Speech", copy: "Support clear expression and verified signs", Icon: MessageCircle, tone: "bg-speech-tint text-speech" },
];
export function FoundationPreview() {
  const profile = useAccessibilityStore((state) => state.profile); const setNeed = useAccessibilityStore((state) => state.setNeed); const announcement = useAccessibilityStore((state) => state.announcement);
  const modules = resolveDashboard(profile, { now: Date.now() }); const needs = selectedNeeds(profile);
  const set = (need: Need) => setNeed(need, !profile[need]);
  return <div className="min-h-dvh bg-canvas px-4 py-8 sm:py-12"><div className="mx-auto max-w-3xl"><header className="flex items-center justify-between"><div><p className="text-xl font-extrabold text-primary">INAI</p><p className="text-xs font-semibold text-muted-foreground">Adaptive AI Accessibility Companion</p></div><span className="inline-flex items-center gap-2 rounded-full bg-hearing-tint px-3 py-2 text-xs font-extrabold text-hearing"><span className="size-2 rounded-full bg-live"/>Foundation ready</span></header>
    <section className="mt-8 grid items-center gap-6 rounded-card bg-background p-6 shadow-inai sm:grid-cols-[1fr_13rem] sm:p-8"><div><span className="inline-flex items-center gap-2 rounded-full bg-primary-tint px-3 py-2 text-xs font-bold text-primary"><Sparkles className="size-4" aria-hidden="true"/>One companion, shaped around you</span><h1 className="mt-4 max-w-xl text-3xl font-extrabold leading-tight sm:text-4xl">How can I support you?</h1><p className="mt-3 max-w-xl text-base leading-7 text-muted-foreground">Choose any combination. INAI updates the experience immediately, without making assumptions about you.</p></div><INAIAvatar state="idle" size="md" speech={announcement}/></section>
    <section aria-labelledby="needs-heading" className="mt-8"><div className="flex items-end justify-between gap-4"><div><h2 id="needs-heading" className="text-xl font-extrabold">Your support profile</h2><p className="mt-1 text-sm text-muted-foreground">Select more than one if that feels right.</p></div><span className="text-sm font-bold text-primary">{needs.length} selected</span></div><div className="mt-4 grid gap-3 sm:grid-cols-3">{options.map(({ id, label, copy, Icon, tone }) => <button type="button" key={id} aria-pressed={profile[id]} onClick={() => set(id)} className={`relative min-h-44 rounded-card border-2 p-5 text-left transition-transform hover:-translate-y-0.5 focus-visible:outline-none focus-visible:ring-3 focus-visible:ring-ring ${profile[id] ? "border-primary bg-background shadow-inai" : "border-line bg-background"}`}><span className={`grid size-12 place-items-center rounded-control ${tone}`}><Icon aria-hidden="true"/></span><span className="mt-5 block text-lg font-extrabold">{label}</span><span className="mt-1 block text-sm leading-6 text-muted-foreground">{copy}</span><span className={`absolute right-4 top-4 grid size-7 place-items-center rounded-full border-2 ${profile[id] ? "border-primary bg-primary text-primary-foreground" : "border-line bg-background"}`}>{profile[id] && <Check className="size-4" aria-hidden="true"/>}</span></button>)}</div></section>
    <section aria-labelledby="modules-heading" className="mt-8 rounded-card bg-background p-6 shadow-inai"><div className="flex flex-wrap items-center justify-between gap-3"><div><h2 id="modules-heading" className="text-xl font-extrabold">Live adaptive dashboard</h2><p className="mt-1 text-sm text-muted-foreground">Priority order updates from your profile.</p></div><ModeBadge mode="REAL"/></div><ol className="mt-5 grid gap-3 sm:grid-cols-2">{modules.map((module, index) => <li key={module.id} className={`${index === 0 ? "sm:col-span-2 bg-primary-tint" : "bg-canvas"} rounded-control border border-line p-4`}><span className="text-xs font-extrabold text-primary">{module.size.toUpperCase()}</span><p className="mt-1 font-bold">{module.title}</p></li>)}</ol></section>
    <footer className="mt-8 flex flex-col items-center gap-4 text-center"><div className="flex items-center gap-2 text-sm font-semibold text-muted-foreground"><ShieldCheck className="size-5 text-live" aria-hidden="true"/>Simulated capabilities are always clearly marked.</div><Button type="button" onClick={() => setNeed("visual", true)}>Continue with this profile</Button><p aria-hidden="true" className="hidden rotate-[-5deg] font-hand text-xl text-primary/50 min-[360px]:block">Let's make this world more inclusive — together!</p></footer><CaptionRegion message={announcement}/></div></div>;
}
